# Generated by Django 6.0.4 on 2026-05-03 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='catalog.component')),
                ('socket', models.CharField(max_length=50, verbose_name='Сокет')),
                ('cores', models.IntegerField(verbose_name='Ядра')),
                ('threads', models.IntegerField(verbose_name='Потоки')),
                ('base_clock_ghz', models.FloatField(verbose_name='Базовая частота (ГГц)')),
                ('boost_clock_ghz', models.FloatField(verbose_name='Макс. частота (ГГц)')),
                ('l3_cache_mb', models.FloatField(verbose_name='L3 Кэш (МБ)')),
                ('tdp', models.IntegerField(verbose_name='TDP (Вт)')),
                ('integrated_graphics', models.BooleanField(default=False, verbose_name='Встроенная графика')),
                ('max_memory_gb', models.IntegerField(verbose_name='Макс. объем памяти (ГБ)')),
                ('memory_channels', models.IntegerField(verbose_name='Каналы памяти')),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='catalog.component')),
                ('type', models.CharField(max_length=20, verbose_name='Тип (DDR)')),
                ('capacity_gb', models.IntegerField(verbose_name='Объем (ГБ)')),
                ('speed_mhz', models.IntegerField(verbose_name='Частота (МГц)')),
                ('timings', models.CharField(max_length=50, verbose_name='Тайминги')),
                ('voltage', models.FloatField(verbose_name='Напряжение (В)')),
            ],
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='catalog.component')),
                ('socket', models.CharField(max_length=50, verbose_name='Сокет')),
                ('chipset', models.CharField(max_length=50, verbose_name='Чипсет')),
                ('form_factor', models.CharField(max_length=50, verbose_name='Форм-фактор')),
                ('ram_slots', models.IntegerField(verbose_name='Слоты RAM')),
                ('ram_max_gb', models.IntegerField(verbose_name='Макс. RAM (ГБ)')),
                ('ram_type', models.CharField(max_length=20, verbose_name='Тип RAM')),
                ('ram_speed_mhz', models.IntegerField(verbose_name='Макс. частота RAM (МГц)')),
                ('pcie_ver', models.CharField(max_length=10, verbose_name='Версия PCIe')),
                ('pcie_slots', models.IntegerField(verbose_name='Слоты PCIe')),
                ('m2_slots', models.IntegerField(verbose_name='Слоты M.2')),
                ('m2_type', models.CharField(max_length=50, verbose_name='Тип M.2')),
                ('sata_ports', models.IntegerField(verbose_name='Порты SATA')),
                ('wifi', models.BooleanField(default=False, verbose_name='Wi-Fi')),
                ('bluetooth', models.BooleanField(default=False, verbose_name='Bluetooth')),
            ],
        ),
        migrations.CreateModel(
            name='PowerSupply',
            fields=[
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='catalog.component')),
                ('wattage', models.IntegerField(verbose_name='Мощность (Вт)')),
                ('efficiency_rating', models.CharField(max_length=50, verbose_name='Сертификат')),
                ('connectors_sata', models.IntegerField(verbose_name='Разъемы SATA')),
            ],
        ),
        migrations.CreateModel(
            name='VideoCard',
            fields=[
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='catalog.component')),
                ('chipset', models.CharField(max_length=100, verbose_name='Чипсет ГП')),
                ('capacity_gb', models.IntegerField(verbose_name='Объем памяти (ГБ)')),
                ('pcie_version', models.CharField(max_length=20, verbose_name='Интерфейс PCIe')),
                ('form_factor', models.CharField(max_length=50, verbose_name='Форм-фактор')),
                ('tdp', models.IntegerField(verbose_name='TDP (Вт)')),
                ('power_connectors', models.CharField(max_length=100, verbose_name='Разъемы питания')),
                ('length_mm', models.IntegerField(verbose_name='Длина (мм)')),
                ('outputs', models.CharField(max_length=100, verbose_name='Видеовыходы')),
                ('boost_clock_mhz', models.IntegerField(verbose_name='Частота (МГц)')),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название сборки')),
                ('is_public', models.BooleanField(default=False, verbose_name='Опубликовано (в каталоге)')),
                ('total_power_calc', models.IntegerField(default=0, verbose_name='Расчетная мощность')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.component')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.configuration')),
            ],
            options={
                'unique_together': {('configuration', 'component')},
            },
        ),
    ]
