# Generated by Django 4.2.30 on 2026-05-10 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPU_Cooler',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.component')),
                ('height', models.IntegerField()),
                ('fan_speed', models.CharField(max_length=100)),
                ('noise_level', models.FloatField()),
                ('tdp', models.IntegerField()),
                ('socket', models.CharField(max_length=255)),
            ],
            bases=('catalog.component',),
        ),
        migrations.CreateModel(
            name='Power_Supply',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.component')),
                ('wattage', models.IntegerField()),
                ('efficiency_rating', models.CharField(max_length=100)),
                ('connectors_24pin', models.IntegerField(default=1)),
                ('connectors_cpu4_4pin', models.IntegerField(default=0)),
                ('connectors_cpu_8pin', models.IntegerField(default=0)),
                ('connectors_pcie_6_2pin', models.IntegerField(default=0)),
                ('connectors_pcie_8pin', models.IntegerField(default=0)),
                ('connectors_pcie_12pin', models.IntegerField(default=0)),
                ('connectors_sata', models.IntegerField(default=0)),
            ],
            bases=('catalog.component',),
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.component')),
                ('type', models.CharField(max_length=50)),
                ('form_factor', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('interface', models.CharField(max_length=50)),
                ('read_speed', models.IntegerField()),
                ('write_speed', models.IntegerField()),
            ],
            bases=('catalog.component',),
        ),
        migrations.RenameModel(
            old_name='ConfigItem',
            new_name='Config_Item',
        ),
        migrations.AlterModelOptions(
            name='config_item',
            options={'verbose_name': 'Config Item', 'verbose_name_plural': 'Config Items'},
        ),
        migrations.AlterUniqueTogether(
            name='config_item',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='total_power_calc',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='component',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='max_memory_gb',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='capacity_gb',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='component',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='component',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='ram_max_gb',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='ram_speed_mhz',
        ),
        migrations.RemoveField(
            model_name='videocard',
            name='boost_clock_mhz',
        ),
        migrations.RemoveField(
            model_name='videocard',
            name='capacity_gb',
        ),
        migrations.RemoveField(
            model_name='videocard',
            name='component',
        ),
        migrations.RemoveField(
            model_name='videocard',
            name='length_mm',
        ),
        migrations.RemoveField(
            model_name='videocard',
            name='pcie_version',
        ),
        migrations.AddField(
            model_name='component',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='configuration',
            name='total_power',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cpu',
            name='component_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.component'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memory',
            name='capacity',
            field=models.IntegerField(default=1, help_text='Total capacity in GB'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memory',
            name='component_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.component'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motherboard',
            name='component_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.component'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motherboard',
            name='ram_max',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motherboard',
            name='ram_speed',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videocard',
            name='boost_clock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videocard',
            name='capacity',
            field=models.IntegerField(default=1, help_text='VRAM size in GB'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videocard',
            name='component_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.component'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videocard',
            name='gpu_chip',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videocard',
            name='length',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videocard',
            name='pcie',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='component',
            name='manufacturer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='base_clock_ghz',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='boost_clock_ghz',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cores',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='integrated_graphics',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='l3_cache_mb',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='memory_channels',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='socket',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='tdp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='threads',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='memory',
            name='speed_mhz',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='memory',
            name='timings',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='memory',
            name='type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='memory',
            name='voltage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='bluetooth',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='chipset',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='form_factor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='m2_slots',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='m2_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='pcie_slots',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='pcie_ver',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='ram_slots',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='ram_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='sata_ports',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='socket',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='chipset',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='form_factor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='outputs',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='power_connectors',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='tdp',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='PowerSupply',
        ),
    ]
