# Generated by Django 4.2.30 on 2026-05-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_cpu_cooler_power_supply_storage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config_item',
            options={},
        ),
        migrations.RemoveField(
            model_name='component',
            name='price',
        ),
        migrations.AlterField(
            model_name='memory',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='power_supply',
            name='connectors_24pin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='power_supply',
            name='connectors_cpu4_4pin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='power_supply',
            name='connectors_cpu_8pin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='power_supply',
            name='connectors_pcie_12pin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='power_supply',
            name='connectors_pcie_6_2pin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='power_supply',
            name='connectors_pcie_8pin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='power_supply',
            name='connectors_sata',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='capacity',
            field=models.IntegerField(),
        ),
    ]
