# Generated by Django 4.2.30 on 2026-05-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_config_item_options_remove_component_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
