# Generated by Django 4.2.30 on 2026-05-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_configuration_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='cooler_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='configuration',
            name='has_rgb',
            field=models.BooleanField(default=False),
        ),
    ]
