version: '3.8'

services:
  db:
    image: postgres:15
    env_file:
      - .env  # Передаем переменные в базу
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: ./backend
    env_file:
      - .env  # Передаем переменные в Django
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: